repositories:

- name: cilium
  url: https://helm.cilium.io/
- name: argo
  url: https://argoproj.github.io/argo-helm

releases:

  - name: argocd
    namespace: kcef-system
    chart: argo/argo-cd
    version: 7.3.3
    values:
      - configs:
          params:
            application.namespaces: "kcef-system"

  - name: kcef-system
    namespace: kcef-system
    chart: ./charts/kcef-system/
    version: 0.1.0

  - name: cilium
    namespace: kcef-system
    chart: cilium/cilium
    version: 1.15.7
    values:
         - routingMode: native
         - ipam:
             mode: kubernetes
         - endpointRoutes:
             enabled: true
         - ipv4NativeRoutingCIDR: 10.0.0.0/8
         - ipv6:
             enabled: true
         - ipv6NativeRoutingCIDR: fd30:cccc::/16

         # their nat implementation chooses a random source address. so we need to use nftables
         - enableIPv4Masquerade: false
         - enableIPv6Masquerade: false
         - bpf:
             hostLegacyRouting: true

         # the kube-proxy replacement seems to work well
         - kubeProxyReplacement: true
         - k8sServiceHost: k8s
         - k8sServicePort: 4443

         # our underlay is l3, and this installs unresolveable ip neigh entries
         - l2NeighDiscovery:
             enabled: false
