apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux
  namespace: foundations
spec:
  releaseName: flux
  serviceAccountName: foundations-admin
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: flux2
      version: "2.13.0"
      sourceRef:
        kind: HelmRepository
        name: fluxcd
        namespace: foundations
  valuesFrom:
    - kind: ConfigMap
      name: foundations-config
      valuesKey: flux.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluxcd
  namespace: foundations
spec:
  interval: 1h0m0s
  url: https://fluxcd-community.github.io/helm-charts
