apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress
  namespace: foundations
spec:
  releaseName: ingress
  chart:
    spec:
      chart: kubernetes-ingress
      version: "1.40.*"
      sourceRef:
        kind: HelmRepository
        name: haproxy
        namespace: foundations
  interval: 1h0m0s
  install:
    createNamespace: true
  values: {}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: haproxy
  namespace: foundations
spec:
  interval: 1h0m0s
  url: https://haproxytech.github.io/helm-charts
