apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: kcef-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: kcef-system
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: "7.3.*"
    chart: argo-cd
    helm:
      valuesObject:
        applicationSet:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
        notification:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
        repoServer:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
        redis:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
        dex:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
        controller:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
        configs:
          params:
            application.namespaces: "kcef-system"
          cm:
            "resource.exclusions": |
              - apiGroups:
                  - cilium.io
                kinds:
                  - CiliumIdentity
                clusters:
                  - "*"

  destination:
    server: https://kubernetes.default.svc
    namespace: kcef-system
  syncPolicy:
    automated:
      selfHeal: true
