apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: kcef-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: kcef-system
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: "7.3.*"
    chart: argo-cd
    helm:
      valuesObject:
        applicationSet:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
        notification:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
        repoServer:
          env:
            - name: HELM_PLUGINS
              value: /custom-tools/helm-plugins/
            - name: HELM_SECRETS_CURL_PATH
              value: /custom-tools/curl
            - name: HELM_SECRETS_SOPS_PATH
              value: /custom-tools/sops
            - name: HELM_SECRETS_VALS_PATH
              value: /custom-tools/vals
            - name: HELM_SECRETS_KUBECTL_PATH
              value: /custom-tools/kubectl
            - name: HELM_SECRETS_BACKEND
              value: vals
            - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
              value: "false"
            - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
              value: "true"
            - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
              value: "false"
            - name: HELM_SECRETS_WRAPPER_ENABLED
              value: "true"
            - name: HELM_SECRETS_DECRYPT_SECRETS_IN_TMP_DIR
              value: "true"
            - name: HELM_SECRETS_HELM_PATH
              value: /usr/local/bin/helm
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          volumes:
            - name: custom-tools
              emptyDir: {}
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
            - mountPath: /usr/local/sbin/helm
              subPath: helm
              name: custom-tools
          initContainers:
            - name: download-tools
              image: alpine:latest
              imagePullPolicy: IfNotPresent
              command: [sh, -ec]
              env:
                - name: HELM_SECRETS_VERSION
                  value: "4.6.0"
                - name: KUBECTL_VERSION
                  value: "1.30.1"
                - name: VALS_VERSION
                  value: "0.37.3"
                - name: SOPS_VERSION
                  value: "3.9.0"
              args:
                - |
                  set -x
                  mkdir -p /custom-tools/helm-plugins
                  wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v${HELM_SECRETS_VERSION}/helm-secrets.tar.gz | tar -C /custom-tools/helm-plugins -xzf-;

                  wget -qO /custom-tools/curl https://github.com/moparisthebest/static-curl/releases/latest/download/curl-amd64
                  wget -qO /custom-tools/sops https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64
                  wget -qO /custom-tools/kubectl https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl

                  wget -qO- https://github.com/helmfile/vals/releases/download/v${VALS_VERSION}/vals_${VALS_VERSION}_linux_amd64.tar.gz | tar -xzf- -C /custom-tools/ vals;

                  cp /custom-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /custom-tools/helm

                  chmod +x /custom-tools/*
              volumeMounts:
                - mountPath: /custom-tools
                  name: custom-tools
        redis:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
        dex:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
        controller:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
        configs:
          params:
            application.namespaces: "kcef-system"
          cm:
            "helm.valuesFileSchemes": |
              secrets+gpg-import, secrets+gpg-import-kubernetes,
              secrets+age-import, secrets+age-import-kubernetes,
              secrets, secrets+literal,
              https
            "resource.exclusions": |
              - apiGroups:
                  - cilium.io
                kinds:
                  - CiliumIdentity
                clusters:
                  - "*"

  destination:
    server: https://kubernetes.default.svc
    namespace: kcef-system
  syncPolicy:
    automated:
      selfHeal: true
