apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: kcef-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: kcef-system
  source:
    repoURL: https://openebs.github.io/openebs
    targetRevision: "4.1.0"
    chart: openebs
    helm:
      valuesObject:
        engines:
          replicated:
            mayastor:
              enabled: false
        localpv-provisioner:
          analytics:
            enabled: false
        lvm-localpv:
          analytics:
            enabled: false
        zfs-localpv:
          analytics:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kcef-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
