---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kcef
  namespace: kcef-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Kubernetes Cloud Enterprise Foundations
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - foundations
