apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: kcef-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: kcef
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "56.8.2"
    chart: kube-prometheus-stack
    helm:
      valuesObject:
        grafana:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kcef-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      # https://blog.ediri.io/kube-prometheus-stack-and-argocd-25-server-side-apply-to-the-rescue
      - ServerSideApply=true
