---
apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Chart.Name}}-postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.3
          env:
            - name: POSTGRES_USER 
              value: postgres
            - name: POSTGRES_PASSWORD
              value: {{.Values.postgres.password }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data
          {{- if .Values.migrationMode }}
          command:
            - /bin/sleep
            - inf
          {{- else }}
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U postgres -h 127.0.0.1
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U postgres -h 127.0.0.1
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U postgres -h 127.0.0.1
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: postgres
      spec:
        {{- if .Values.nextcloud.storageClassName }}
        storageClassName: {{.Values.postgres.storageClassName }}
        {{- end }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{.Values.postgres.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-nextcloud
  labels:
    app: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Chart.Name}}-nextcloud
spec:
  serviceName: nextcloud
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      runtimeClassName: kata-qemu-snp
      containers:
        - name: nextcloud
          image: nextcloud:{{.Values.nextcloud.version}}-apache
          env:
            - name: OVERWRITEPROTOCOL
              value: https
            - name: TRUSTED_PROXIES
              value: "*"
            - name: PHP_MEMORY_LIMIT
              value: 10G
            - name: PHP_UPLOAD_LIMIT
              value: 100G
            - name: POSTGRES_HOST
              value: {{.Chart.Name}}-postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER 
              value: nextcloud
            - name: POSTGRES_PASSWORD
              value: {{.Values.postgres.password }}
          ports:
            - containerPort: 80
              name: nextcloud
          volumeMounts:
            - name: nextcloud
              mountPath: /var/www/html
          {{- if .Values.migrationMode }}
          command:
            - /bin/sleep
            - inf
          {{- else }}
          livenessProbe:
            httpGet:
              path: /status.php
              port: 80
              httpHeaders:
              - name: Host
                value: {{ $.Values.nextcloud.domain | quote }}
          readinessProbe:
            httpGet:
              path: /status.php
              port: 80
              httpHeaders:
              - name: Host
                value: {{ $.Values.nextcloud.domain | quote }}
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: nextcloud
      spec:
        {{- if .Values.nextcloud.storageClassName }}
        storageClassName: {{.Values.nextcloud.storageClassName }}
        {{- end }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{.Values.nextcloud.storageSize }}

